import type { ComponentRegistry } from '@/components/ui/ui-builder/types';
import { z } from 'zod';
import { motion, AnimatePresence, LayoutGroup } from 'motion/react';
import { commonFieldOverrides, childrenAsTextareaFieldOverrides, classNameFieldOverrides } from '@/lib/ui-builder/registry/form-field-overrides';

// Define Zod schemas for Framer Motion components
const MotionDivSchema = z.object({
  className: z.string().optional(),
  children: z.any().optional(),
  animate: z.any().optional(),
  initial: z.any().optional(),
  exit: z.any().optional(),
  transition: z.any().optional(),
  layout: z.boolean().optional(),
  layoutId: z.string().optional(),
  variants: z.any().optional(),
  whileHover: z.any().optional(),
  whileTap: z.any().optional(),
  whileFocus: z.any().optional(),
  whileDrag: z.any().optional(),
  whileInView: z.any().optional(),
  viewport: z.any().optional(),
  custom: z.any().optional(),
  key: z.string().optional(),
  style: z.any().optional(),
  variantsType: z.enum(['spring', 'inertia', 'tween', 'keyframes']).optional(),
});

const MotionButtonSchema = z.object({
  className: z.string().optional(),
  children: z.any().optional(),
  animate: z.any().optional(),
  initial: z.any().optional(),
  exit: z.any().optional(),
  transition: z.any().optional(),
  layout: z.boolean().optional(),
  layoutId: z.string().optional(),
  variants: z.any().optional(),
  whileHover: z.any().optional(),
  whileTap: z.any().optional(),
  whileFocus: z.any().optional(),
  whileDrag: z.any().optional(),
  whileInView: z.any().optional(),
  viewport: z.any().optional(),
  custom: z.any().optional(),
  key: z.string().optional(),
  style: z.any().optional(),
  variantsType: z.enum(['spring', 'inertia', 'tween', 'keyframes']).optional(),
  type: z.enum(['button', 'submit', 'reset']).default('button'),
  disabled: z.boolean().optional(),
});

const MotionImgSchema = z.object({
  className: z.string().optional(),
  src: z.string().default("https://placehold.co/200"),
  alt: z.string().optional(),
  width: z.coerce.number().optional(),
  height: z.coerce.number().optional(),
  animate: z.any().optional(),
  initial: z.any().optional(),
  exit: z.any().optional(),
  transition: z.any().optional(),
  layout: z.boolean().optional(),
  layoutId: z.string().optional(),
  variants: z.any().optional(),
  whileHover: z.any().optional(),
  whileTap: z.any().optional(),
  whileFocus: z.any().optional(),
  whileDrag: z.any().optional(),
  whileInView: z.any().optional(),
  viewport: z.any().optional(),
  custom: z.any().optional(),
  key: z.string().optional(),
  style: z.any().optional(),
  variantsType: z.enum(['spring', 'inertia', 'tween', 'keyframes']).optional(),
});

const MotionH1Schema = z.object({
  className: z.string().optional(),
  children: z.string().optional(),
  animate: z.any().optional(),
  initial: z.any().optional(),
  exit: z.any().optional(),
  transition: z.any().optional(),
  layout: z.boolean().optional(),
  layoutId: z.string().optional(),
  variants: z.any().optional(),
  whileHover: z.any().optional(),
  whileTap: z.any().optional(),
  whileFocus: z.any().optional(),
  whileDrag: z.any().optional(),
  whileInView: z.any().optional(),
  viewport: z.any().optional(),
  custom: z.any().optional(),
  key: z.string().optional(),
  style: z.any().optional(),
  variantsType: z.enum(['spring', 'inertia', 'tween', 'keyframes']).optional(),
});

const MotionH2Schema = z.object({
  className: z.string().optional(),
  children: z.string().optional(),
  animate: z.any().optional(),
  initial: z.any().optional(),
  exit: z.any().optional(),
  transition: z.any().optional(),
  layout: z.boolean().optional(),
  layoutId: z.string().optional(),
  variants: z.any().optional(),
  whileHover: z.any().optional(),
  whileTap: z.any().optional(),
  whileFocus: z.any().optional(),
  whileDrag: z.any().optional(),
  whileInView: z.any().optional(),
  viewport: z.any().optional(),
  custom: z.any().optional(),
  key: z.string().optional(),
  style: z.any().optional(),
  variantsType: z.enum(['spring', 'inertia', 'tween', 'keyframes']).optional(),
});

const MotionH3Schema = z.object({
  className: z.string().optional(),
  children: z.string().optional(),
  animate: z.any().optional(),
  initial: z.any().optional(),
  exit: z.any().optional(),
  transition: z.any().optional(),
  layout: z.boolean().optional(),
  layoutId: z.string().optional(),
  variants: z.any().optional(),
  whileHover: z.any().optional(),
  whileTap: z.any().optional(),
  whileFocus: z.any().optional(),
  whileDrag: z.any().optional(),
  whileInView: z.any().optional(),
  viewport: z.any().optional(),
  custom: z.any().optional(),
  key: z.string().optional(),
  style: z.any().optional(),
  variantsType: z.enum(['spring', 'inertia', 'tween', 'keyframes']).optional(),
});

const MotionPSchema = z.object({
  className: z.string().optional(),
  children: z.string().optional(),
  animate: z.any().optional(),
  initial: z.any().optional(),
  exit: z.any().optional(),
  transition: z.any().optional(),
  layout: z.boolean().optional(),
  layoutId: z.string().optional(),
  variants: z.any().optional(),
  whileHover: z.any().optional(),
  whileTap: z.any().optional(),
  whileFocus: z.any().optional(),
  whileDrag: z.any().optional(),
  whileInView: z.any().optional(),
  viewport: z.any().optional(),
  custom: z.any().optional(),
  key: z.string().optional(),
  style: z.any().optional(),
  variantsType: z.enum(['spring', 'inertia', 'tween', 'keyframes']).optional(),
});

const AnimatePresenceSchema = z.object({
  children: z.any().optional(),
  initial: z.boolean().default(true),
  onExitComplete: z.any().optional(),
  custom: z.any().optional(),
});

const LayoutGroupSchema = z.object({
  children: z.any().optional(),
  id: z.string().optional(),
});

export const framerMotionComponentDefinitions: ComponentRegistry = {
  // Motion components for different HTML elements
  MotionDiv: {
    component: motion.div,
    schema: MotionDivSchema,
    from: 'framer-motion',
    fieldOverrides: commonFieldOverrides(),
    defaultChildren: 'Animated Content',
  },
  MotionSpan: {
    component: motion.span,
    schema: z.object({
      className: z.string().optional(),
      children: z.any().optional(),
      animate: z.any().optional(),
      initial: z.any().optional(),
      exit: z.any().optional(),
      transition: z.any().optional(),
      layout: z.boolean().optional(),
      layoutId: z.string().optional(),
      variants: z.any().optional(),
      whileHover: z.any().optional(),
      whileTap: z.any().optional(),
      whileFocus: z.any().optional(),
      whileDrag: z.any().optional(),
      whileInView: z.any().optional(),
      viewport: z.any().optional(),
      custom: z.any().optional(),
      key: z.string().optional(),
      style: z.any().optional(),
      variantsType: z.enum(['spring', 'inertia', 'tween', 'keyframes']).optional(),
    }),
    from: 'framer-motion',
    fieldOverrides: {
      className: (layer) => classNameFieldOverrides(layer),
      children: (layer) => childrenAsTextareaFieldOverrides(layer),
    },
    defaultChildren: 'Animated Text',
  },
  MotionButton: {
    component: motion.button,
    schema: MotionButtonSchema,
    from: 'framer-motion',
    fieldOverrides: commonFieldOverrides(),
    defaultChildren: 'Animated Button',
  },
  MotionImg: {
    component: motion.img,
    schema: MotionImgSchema,
    from: 'framer-motion',
    fieldOverrides: {
      className: (layer) => classNameFieldOverrides(layer),
    },
    defaultChildren: [],
  },
  MotionH1: {
    component: motion.h1,
    schema: MotionH1Schema,
    from: 'framer-motion',
    fieldOverrides: {
      ...commonFieldOverrides(),
      children: (layer) => childrenAsTextareaFieldOverrides(layer),
    },
    defaultChildren: 'Animated Heading 1',
  },
  MotionH2: {
    component: motion.h2,
    schema: MotionH2Schema,
    from: 'framer-motion',
    fieldOverrides: {
      ...commonFieldOverrides(),
      children: (layer) => childrenAsTextareaFieldOverrides(layer),
    },
    defaultChildren: 'Animated Heading 2',
  },
  MotionH3: {
    component: motion.h3,
    schema: MotionH3Schema,
    from: 'framer-motion',
    fieldOverrides: {
      ...commonFieldOverrides(),
      children: (layer) => childrenAsTextareaFieldOverrides(layer),
    },
    defaultChildren: 'Animated Heading 3',
  },
  MotionP: {
    component: motion.p,
    schema: MotionPSchema,
    from: 'framer-motion',
    fieldOverrides: {
      ...commonFieldOverrides(),
      children: (layer) => childrenAsTextareaFieldOverrides(layer),
    },
    defaultChildren: 'Animated Paragraph',
  },
  MotionA: {
    component: motion.a,
    schema: z.object({
      className: z.string().optional(),
      children: z.any().optional(),
      href: z.string().optional(),
      target: z.enum(['_blank', '_self', '_parent', '_top']).optional().default('_self'),
      rel: z.enum(['noopener', 'noreferrer', 'nofollow']).optional(),
      title: z.string().optional(),
      download: z.boolean().optional().default(false),
      animate: z.any().optional(),
      initial: z.any().optional(),
      exit: z.any().optional(),
      transition: z.any().optional(),
      layout: z.boolean().optional(),
      layoutId: z.string().optional(),
      variants: z.any().optional(),
      whileHover: z.any().optional(),
      whileTap: z.any().optional(),
      whileFocus: z.any().optional(),
      whileDrag: z.any().optional(),
      whileInView: z.any().optional(),
      viewport: z.any().optional(),
      custom: z.any().optional(),
      key: z.string().optional(),
      style: z.any().optional(),
      variantsType: z.enum(['spring', 'inertia', 'tween', 'keyframes']).optional(),
    }),
    from: 'framer-motion',
    fieldOverrides: commonFieldOverrides(),
    defaultChildren: 'Animated Link',
  },
  MotionUl: {
    component: motion.ul,
    schema: z.object({
      className: z.string().optional(),
      children: z.any().optional(),
      animate: z.any().optional(),
      initial: z.any().optional(),
      exit: z.any().optional(),
      transition: z.any().optional(),
      layout: z.boolean().optional(),
      layoutId: z.string().optional(),
      variants: z.any().optional(),
      whileHover: z.any().optional(),
      whileTap: z.any().optional(),
      whileFocus: z.any().optional(),
      whileDrag: z.any().optional(),
      whileInView: z.any().optional(),
      viewport: z.any().optional(),
      custom: z.any().optional(),
      key: z.string().optional(),
      style: z.any().optional(),
      variantsType: z.enum(['spring', 'inertia', 'tween', 'keyframes']).optional(),
    }),
    from: 'framer-motion',
    fieldOverrides: commonFieldOverrides(),
  },
  MotionOl: {
    component: motion.ol,
    schema: z.object({
      className: z.string().optional(),
      children: z.any().optional(),
      animate: z.any().optional(),
      initial: z.any().optional(),
      exit: z.any().optional(),
      transition: z.any().optional(),
      layout: z.boolean().optional(),
      layoutId: z.string().optional(),
      variants: z.any().optional(),
      whileHover: z.any().optional(),
      whileTap: z.any().optional(),
      whileFocus: z.any().optional(),
      whileDrag: z.any().optional(),
      whileInView: z.any().optional(),
      viewport: z.any().optional(),
      custom: z.any().optional(),
      key: z.string().optional(),
      style: z.any().optional(),
      variantsType: z.enum(['spring', 'inertia', 'tween', 'keyframes']).optional(),
    }),
    from: 'framer-motion',
    fieldOverrides: commonFieldOverrides(),
  },
  MotionLi: {
    component: motion.li,
    schema: z.object({
      className: z.string().optional(),
      children: z.any().optional(),
      animate: z.any().optional(),
      initial: z.any().optional(),
      exit: z.any().optional(),
      transition: z.any().optional(),
      layout: z.boolean().optional(),
      layoutId: z.string().optional(),
      variants: z.any().optional(),
      whileHover: z.any().optional(),
      whileTap: z.any().optional(),
      whileFocus: z.any().optional(),
      whileDrag: z.any().optional(),
      whileInView: z.any().optional(),
      viewport: z.any().optional(),
      custom: z.any().optional(),
      key: z.string().optional(),
      style: z.any().optional(),
      variantsType: z.enum(['spring', 'inertia', 'tween', 'keyframes']).optional(),
    }),
    from: 'framer-motion',
    fieldOverrides: {
      ...commonFieldOverrides(),
      children: (layer) => childrenAsTextareaFieldOverrides(layer),
    },
    defaultChildren: 'Animated List Item',
  },
  MotionInput: {
    component: motion.input,
    schema: z.object({
      className: z.string().optional(),
      value: z.string().optional(),
      placeholder: z.string().optional(),
      type: z.enum(['text', 'email', 'password', 'number', 'tel', 'url', 'search']).default('text'),
      disabled: z.boolean().optional(),
      animate: z.any().optional(),
      initial: z.any().optional(),
      exit: z.any().optional(),
      transition: z.any().optional(),
      layout: z.boolean().optional(),
      layoutId: z.string().optional(),
      variants: z.any().optional(),
      whileHover: z.any().optional(),
      whileTap: z.any().optional(),
      whileFocus: z.any().optional(),
      whileDrag: z.any().optional(),
      whileInView: z.any().optional(),
      viewport: z.any().optional(),
      custom: z.any().optional(),
      key: z.string().optional(),
      style: z.any().optional(),
      variantsType: z.enum(['spring', 'inertia', 'tween', 'keyframes']).optional(),
    }),
    from: 'framer-motion',
    fieldOverrides: {
      className: (layer) => classNameFieldOverrides(layer),
    },
  },
  MotionLabel: {
    component: motion.label,
    schema: z.object({
      className: z.string().optional(),
      children: z.any().optional(),
      htmlFor: z.string().optional(),
      animate: z.any().optional(),
      initial: z.any().optional(),
      exit: z.any().optional(),
      transition: z.any().optional(),
      layout: z.boolean().optional(),
      layoutId: z.string().optional(),
      variants: z.any().optional(),
      whileHover: z.any().optional(),
      whileTap: z.any().optional(),
      whileFocus: z.any().optional(),
      whileDrag: z.any().optional(),
      whileInView: z.any().optional(),
      viewport: z.any().optional(),
      custom: z.any().optional(),
      key: z.string().optional(),
      style: z.any().optional(),
      variantsType: z.enum(['spring', 'inertia', 'tween', 'keyframes']).optional(),
    }),
    from: 'framer-motion',
    fieldOverrides: {
      ...commonFieldOverrides(),
      children: (layer) => childrenAsTextareaFieldOverrides(layer),
    },
    defaultChildren: 'Animated Label',
  },
  MotionSection: {
    component: motion.section,
    schema: z.object({
      className: z.string().optional(),
      children: z.any().optional(),
      animate: z.any().optional(),
      initial: z.any().optional(),
      exit: z.any().optional(),
      transition: z.any().optional(),
      layout: z.boolean().optional(),
      layoutId: z.string().optional(),
      variants: z.any().optional(),
      whileHover: z.any().optional(),
      whileTap: z.any().optional(),
      whileFocus: z.any().optional(),
      whileDrag: z.any().optional(),
      whileInView: z.any().optional(),
      viewport: z.any().optional(),
      custom: z.any().optional(),
      key: z.string().optional(),
      style: z.any().optional(),
      variantsType: z.enum(['spring', 'inertia', 'tween', 'keyframes']).optional(),
    }),
    from: 'framer-motion',
    fieldOverrides: commonFieldOverrides(),
  },
  MotionHeader: {
    component: motion.header,
    schema: z.object({
      className: z.string().optional(),
      children: z.any().optional(),
      animate: z.any().optional(),
      initial: z.any().optional(),
      exit: z.any().optional(),
      transition: z.any().optional(),
      layout: z.boolean().optional(),
      layoutId: z.string().optional(),
      variants: z.any().optional(),
      whileHover: z.any().optional(),
      whileTap: z.any().optional(),
      whileFocus: z.any().optional(),
      whileDrag: z.any().optional(),
      whileInView: z.any().optional(),
      viewport: z.any().optional(),
      custom: z.any().optional(),
      key: z.string().optional(),
      style: z.any().optional(),
      variantsType: z.enum(['spring', 'inertia', 'tween', 'keyframes']).optional(),
    }),
    from: 'framer-motion',
    fieldOverrides: commonFieldOverrides(),
  },
  MotionFooter: {
    component: motion.footer,
    schema: z.object({
      className: z.string().optional(),
      children: z.any().optional(),
      animate: z.any().optional(),
      initial: z.any().optional(),
      exit: z.any().optional(),
      transition: z.any().optional(),
      layout: z.boolean().optional(),
      layoutId: z.string().optional(),
      variants: z.any().optional(),
      whileHover: z.any().optional(),
      whileTap: z.any().optional(),
      whileFocus: z.any().optional(),
      whileDrag: z.any().optional(),
      whileInView: z.any().optional(),
      viewport: z.any().optional(),
      custom: z.any().optional(),
      key: z.string().optional(),
      style: z.any().optional(),
      variantsType: z.enum(['spring', 'inertia', 'tween', 'keyframes']).optional(),
    }),
    from: 'framer-motion',
    fieldOverrides: commonFieldOverrides(),
  },
  MotionNav: {
    component: motion.nav,
    schema: z.object({
      className: z.string().optional(),
      children: z.any().optional(),
      animate: z.any().optional(),
      initial: z.any().optional(),
      exit: z.any().optional(),
      transition: z.any().optional(),
      layout: z.boolean().optional(),
      layoutId: z.string().optional(),
      variants: z.any().optional(),
      whileHover: z.any().optional(),
      whileTap: z.any().optional(),
      whileFocus: z.any().optional(),
      whileDrag: z.any().optional(),
      whileInView: z.any().optional(),
      viewport: z.any().optional(),
      custom: z.any().optional(),
      key: z.string().optional(),
      style: z.any().optional(),
      variantsType: z.enum(['spring', 'inertia', 'tween', 'keyframes']).optional(),
    }),
    from: 'framer-motion',
    fieldOverrides: commonFieldOverrides(),
  },
  MotionArticle: {
    component: motion.article,
    schema: z.object({
      className: z.string().optional(),
      children: z.any().optional(),
      animate: z.any().optional(),
      initial: z.any().optional(),
      exit: z.any().optional(),
      transition: z.any().optional(),
      layout: z.boolean().optional(),
      layoutId: z.string().optional(),
      variants: z.any().optional(),
      whileHover: z.any().optional(),
      whileTap: z.any().optional(),
      whileFocus: z.any().optional(),
      whileDrag: z.any().optional(),
      whileInView: z.any().optional(),
      viewport: z.any().optional(),
      custom: z.any().optional(),
      key: z.string().optional(),
      style: z.any().optional(),
      variantsType: z.enum(['spring', 'inertia', 'tween', 'keyframes']).optional(),
    }),
    from: 'framer-motion',
    fieldOverrides: commonFieldOverrides(),
  },
  MotionAside: {
    component: motion.aside,
    schema: z.object({
      className: z.string().optional(),
      children: z.any().optional(),
      animate: z.any().optional(),
      initial: z.any().optional(),
      exit: z.any().optional(),
      transition: z.any().optional(),
      layout: z.boolean().optional(),
      layoutId: z.string().optional(),
      variants: z.any().optional(),
      whileHover: z.any().optional(),
      whileTap: z.any().optional(),
      whileFocus: z.any().optional(),
      whileDrag: z.any().optional(),
      whileInView: z.any().optional(),
      viewport: z.any().optional(),
      custom: z.any().optional(),
      key: z.string().optional(),
      style: z.any().optional(),
      variantsType: z.enum(['spring', 'inertia', 'tween', 'keyframes']).optional(),
    }),
    from: 'framer-motion',
    fieldOverrides: commonFieldOverrides(),
  },
  MotionMain: {
    component: motion.main,
    schema: z.object({
      className: z.string().optional(),
      children: z.any().optional(),
      animate: z.any().optional(),
      initial: z.any().optional(),
      exit: z.any().optional(),
      transition: z.any().optional(),
      layout: z.boolean().optional(),
      layoutId: z.string().optional(),
      variants: z.any().optional(),
      whileHover: z.any().optional(),
      whileTap: z.any().optional(),
      whileFocus: z.any().optional(),
      whileDrag: z.any().optional(),
      whileInView: z.any().optional(),
      viewport: z.any().optional(),
      custom: z.any().optional(),
      key: z.string().optional(),
      style: z.any().optional(),
      variantsType: z.enum(['spring', 'inertia', 'tween', 'keyframes']).optional(),
    }),
    from: 'framer-motion',
    fieldOverrides: commonFieldOverrides(),
  },
  MotionForm: {
    component: motion.form,
    schema: z.object({
      className: z.string().optional(),
      children: z.any().optional(),
      action: z.string().optional(),
      method: z.enum(['get', 'post']).default('get'),
      animate: z.any().optional(),
      initial: z.any().optional(),
      exit: z.any().optional(),
      transition: z.any().optional(),
      layout: z.boolean().optional(),
      layoutId: z.string().optional(),
      variants: z.any().optional(),
      whileHover: z.any().optional(),
      whileTap: z.any().optional(),
      whileFocus: z.any().optional(),
      whileDrag: z.any().optional(),
      whileInView: z.any().optional(),
      viewport: z.any().optional(),
      custom: z.any().optional(),
      key: z.string().optional(),
      style: z.any().optional(),
      variantsType: z.enum(['spring', 'inertia', 'tween', 'keyframes']).optional(),
    }),
    from: 'framer-motion',
    fieldOverrides: commonFieldOverrides(),
  },
  MotionFieldset: {
    component: motion.fieldset,
    schema: z.object({
      className: z.string().optional(),
      children: z.any().optional(),
      disabled: z.boolean().optional(),
      animate: z.any().optional(),
      initial: z.any().optional(),
      exit: z.any().optional(),
      transition: z.any().optional(),
      layout: z.boolean().optional(),
      layoutId: z.string().optional(),
      variants: z.any().optional(),
      whileHover: z.any().optional(),
      whileTap: z.any().optional(),
      whileFocus: z.any().optional(),
      whileDrag: z.any().optional(),
      whileInView: z.any().optional(),
      viewport: z.any().optional(),
      custom: z.any().optional(),
      key: z.string().optional(),
      style: z.any().optional(),
      variantsType: z.enum(['spring', 'inertia', 'tween', 'keyframes']).optional(),
    }),
    from: 'framer-motion',
    fieldOverrides: commonFieldOverrides(),
  },
  MotionLegend: {
    component: motion.legend,
    schema: z.object({
      className: z.string().optional(),
      children: z.any().optional(),
      animate: z.any().optional(),
      initial: z.any().optional(),
      exit: z.any().optional(),
      transition: z.any().optional(),
      layout: z.boolean().optional(),
      layoutId: z.string().optional(),
      variants: z.any().optional(),
      whileHover: z.any().optional(),
      whileTap: z.any().optional(),
      whileFocus: z.any().optional(),
      whileDrag: z.any().optional(),
      whileInView: z.any().optional(),
      viewport: z.any().optional(),
      custom: z.any().optional(),
      key: z.string().optional(),
      style: z.any().optional(),
      variantsType: z.enum(['spring', 'inertia', 'tween', 'keyframes']).optional(),
    }),
    from: 'framer-motion',
    fieldOverrides: {
      ...commonFieldOverrides(),
      children: (layer) => childrenAsTextareaFieldOverrides(layer),
    },
    defaultChildren: 'Animated Legend',
  },
  MotionSelect: {
    component: motion.select,
    schema: z.object({
      className: z.string().optional(),
      value: z.string().optional(),
      name: z.string().optional(),
      disabled: z.boolean().optional(),
      children: z.any().optional(),
      animate: z.any().optional(),
      initial: z.any().optional(),
      exit: z.any().optional(),
      transition: z.any().optional(),
      layout: z.boolean().optional(),
      layoutId: z.string().optional(),
      variants: z.any().optional(),
      whileHover: z.any().optional(),
      whileTap: z.any().optional(),
      whileFocus: z.any().optional(),
      whileDrag: z.any().optional(),
      whileInView: z.any().optional(),
      viewport: z.any().optional(),
      custom: z.any().optional(),
      key: z.string().optional(),
      style: z.any().optional(),
      variantsType: z.enum(['spring', 'inertia', 'tween', 'keyframes']).optional(),
    }),
    from: 'framer-motion',
    fieldOverrides: commonFieldOverrides(),
  },
  MotionTextarea: {
    component: motion.textarea,
    schema: z.object({
      className: z.string().optional(),
      value: z.string().optional(),
      placeholder: z.string().optional(),
      rows: z.number().optional(),
      cols: z.number().optional(),
      disabled: z.boolean().optional(),
      children: z.any().optional(),
      animate: z.any().optional(),
      initial: z.any().optional(),
      exit: z.any().optional(),
      transition: z.any().optional(),
      layout: z.boolean().optional(),
      layoutId: z.string().optional(),
      variants: z.any().optional(),
      whileHover: z.any().optional(),
      whileTap: z.any().optional(),
      whileFocus: z.any().optional(),
      whileDrag: z.any().optional(),
      whileInView: z.any().optional(),
      viewport: z.any().optional(),
      custom: z.any().optional(),
      key: z.string().optional(),
      style: z.any().optional(),
      variantsType: z.enum(['spring', 'inertia', 'tween', 'keyframes']).optional(),
    }),
    from: 'framer-motion',
    fieldOverrides: {
      ...commonFieldOverrides(),
      value: (layer) => childrenAsTextareaFieldOverrides(layer),
    },
    defaultChildren: 'Animated Textarea',
  },
  AnimatePresence: {
    component: AnimatePresence,
    schema: AnimatePresenceSchema,
    from: 'framer-motion',
    fieldOverrides: commonFieldOverrides(),
  },
  LayoutGroup: {
    component: LayoutGroup,
    schema: LayoutGroupSchema,
    from: 'framer-motion',
    fieldOverrides: commonFieldOverrides(),
  },
};
