import type { SVGMotionProps } from 'framer-motion';
import { z } from 'zod';
import {
  Accessibility,
  Activity,
  Airplay,
  AlarmClock,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUpDown,
  ArrowUp,
  AudioLines,
  Axe,
  Axis3D,
  BadgeCheck,
  BatteryCharging,
  BatteryFull,
  BatteryLow,
  BatteryMedium,
  BellOff,
  BellRing,
  Bell,
  BetweenHorizontalEnd,
  BetweenHorizontalStart,
  BetweenVerticalEnd,
  BetweenVerticalStart,
  Binary,
  Blend,
  Blocks,
  BotMessageSquare,
  BotOff,
  Bot,
  BrushCleaning,
  Brush,
  Cast,
  Cctv,
  ChartBarDecreasing,
  ChartBarIncreasing,
  ChartBar,
  ChartColumnDecreasing,
  ChartColumnIncreasing,
  ChartColumn,
  ChartLine,
  ChartNoAxesColumnDecreasing,
  ChartNoAxesColumnIncreasing,
  ChartNoAxesColumn,
  ChartScatter,
  ChartSpline,
  CheckCheck,
  CheckLine,
  Check,
  Cherry,
  ChevronDown,
  ChevronLeftRight,
  ChevronLeft,
  ChevronRight,
  ChevronUpDown,
  ChevronUp,
  CircleCheckBig,
  CircleCheck,
  CirclePlus,
  CircleX,
  CircuitBoard,
  Clapperboard,
  ClipboardCheck,
  ClipboardList,
  Clipboard,
  Clock1,
  Clock10,
  Clock11,
  Clock12,
  Clock2,
  Clock3,
  Clock4,
  Clock5,
  Clock6,
  Clock7,
  Clock8,
  Clock9,
  Clock,
  CloudDownload,
  CloudDrizzle,
  CloudHail,
  CloudLightning,
  CloudMoonRain,
  CloudMoon,
  CloudRainWind,
  CloudRain,
  CloudSnow,
  CloudSunRain,
  CloudSun,
  CloudUpload,
  Cog,
  Compass,
  Contrast,
  Copy,
  Crop,
  Cross,
  Disc3,
  Download,
  EllipsisVertical,
  Ellipsis,
  EqualNot,
  EvCharger,
  Expand,
  ExternalLink,
  Fan,
  Fingerprint,
  Forklift,
  Frame,
  GalleryHorizontalEnd,
  GalleryHorizontal,
  GalleryVerticalEnd,
  GalleryVertical,
  Gauge,
  Gavel,
  Hammer,
  Heart,
  HouseWifi,
  Kanban,
  Layers2,
  Layers,
  LayoutDashboard,
  LightbulbOff,
  Lightbulb,
  Link2,
  Link,
  List,
  LoaderCircle,
  LoaderPinwheel,
  Loader,
  LockKeyholeOpen,
  LockKeyhole,
  LockOpen,
  Lock,
  LogIn,
  LogOut,
  MapPinOff,
  MapPin,
  Maximize,
  Menu,
  MessageCircleCode,
  MessageCircleDashed,
  MessageCircleHeart,
  MessageCircleMore,
  MessageCircleOff,
  MessageCirclePlus,
  MessageCircleQuestion,
  MessageCircleWarning,
  MessageCircleX,
  MessageCircle,
  MessageSquareCode,
  MessageSquareDashed,
  MessageSquareDiff,
  MessageSquareDot,
  MessageSquareHeart,
  MessageSquareMore,
  MessageSquareOff,
  MessageSquarePlus,
  MessageSquareQuote,
  MessageSquareShare,
  MessageSquareText,
  MessageSquareWarning,
  MessageSquareX,
  MessageSquare,
  Minimize,
  MoonStar,
  Moon,
  MoveDown,
  MoveLeft,
  MoveRight,
  MoveUp,
  Nfc,
  Orbit,
  Paintbrush,
  PanelBottomClose,
  PanelBottomOpen,
  PanelBottom,
  PanelLeftClose,
  PanelLeftOpen,
  PanelLeft,
  PanelRightClose,
  PanelRightOpen,
  PanelRight,
  PanelTopClose,
  PanelTopOpen,
  PanelTop,
  Paperclip,
  PartyPopper,
  Pause,
  PhoneCall,
  Pickaxe,
  PinOff,
  Pin,
  Play,
  PlugZap,
  Plus,
  RadioTower,
  Radio,
  RefreshCcwDot,
  RefreshCcw,
  RefreshCwOff,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Route,
  Router,
  ScissorsLineDashed,
  Scissors,
  Search,
  SendHorizontal,
  Send,
  Settings,
  Shrink,
  SignalHigh,
  SignalLow,
  SignalMedium,
  SignalZero,
  Signal,
  SlidersHorizontal,
  SlidersVertical,
  Sparkle,
  Sparkles,
  SquareArrowOutDownLeft,
  SquareArrowOutDownRight,
  SquareArrowOutUpLeft,
  SquareArrowOutUpRight,
  SquareDashedKanban,
  SquareKanban,
  SquarePlus,
  SquareX,
  Star,
  SunDim,
  SunMedium,
  SunMoon,
  Sun,
  Terminal,
  ThumbsDown,
  ThumbsUp,
  TimerOff,
  Timer,
  ToggleLeft,
  ToggleRight,
  Trash2,
  Trash,
  Unplug,
  Upload,
  UserRound,
  User,
  UsersRound,
  Users,
  Volume1,
  Volume2,
  VolumeOff,
  WifiHigh,
  WifiLow,
  WifiZero,
  Wifi,
  X,
} from '.';

// Define size classes for different icon sizes
const sizeClasses = {
  small: 'h-4 w-4',
  medium: 'h-6 w-6',
  large: 'h-8 w-8',
};

// Define color classes for different icon colors
const colorClasses = {
  accent: 'text-accent',
  accentForeground: 'text-accent-foreground',
  primary: 'text-primary',
  primaryForeground: 'text-primary-foreground',
  secondary: 'text-secondary',
  secondaryForeground: 'text-secondary-foreground',
  destructive: 'text-destructive',
  destructiveForeground: 'text-destructive-foreground',
  muted: 'text-muted',
  mutedForeground: 'text-muted-foreground',
  background: 'text-background',
  foreground: 'text-foreground',
} as const;

// biome-ignore lint/correctness/noUnusedVariables: lint debt cleanup
type Size = keyof typeof sizeClasses;
// biome-ignore lint/correctness/noUnusedVariables: lint debt cleanup
type Color = keyof typeof colorClasses;

const icons = {
  accessibility: Accessibility,
  activity: Activity,
  airplay: Airplay,
  alarmClock: AlarmClock,
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUpDown: ArrowUpDown,
  arrowUp: ArrowUp,
  audioLines: AudioLines,
  axe: Axe,
  axis3D: Axis3D,
  badgeCheck: BadgeCheck,
  batteryCharging: BatteryCharging,
  batteryFull: BatteryFull,
  batteryLow: BatteryLow,
  batteryMedium: BatteryMedium,
  bellOff: BellOff,
  bellRing: BellRing,
  bell: Bell,
  betweenHorizontalEnd: BetweenHorizontalEnd,
  betweenHorizontalStart: BetweenHorizontalStart,
  betweenVerticalEnd: BetweenVerticalEnd,
  betweenVerticalStart: BetweenVerticalStart,
  binary: Binary,
  blend: Blend,
  blocks: Blocks,
  botMessageSquare: BotMessageSquare,
  botOff: BotOff,
  bot: Bot,
  brushCleaning: BrushCleaning,
  brush: Brush,
  cast: Cast,
  cctv: Cctv,
  chartBarDecreasing: ChartBarDecreasing,
  chartBarIncreasing: ChartBarIncreasing,
  chartBar: ChartBar,
  chartColumnDecreasing: ChartColumnDecreasing,
  chartColumnIncreasing: ChartColumnIncreasing,
  chartColumn: ChartColumn,
  chartLine: ChartLine,
  chartNoAxesColumnDecreasing: ChartNoAxesColumnDecreasing,
  chartNoAxesColumnIncreasing: ChartNoAxesColumnIncreasing,
  chartNoAxesColumn: ChartNoAxesColumn,
  chartScatter: ChartScatter,
  chartSpline: ChartSpline,
  checkCheck: CheckCheck,
  checkLine: CheckLine,
  check: Check,
  cherry: Cherry,
  chevronDown: ChevronDown,
  chevronLeftRight: ChevronLeftRight,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUpDown: ChevronUpDown,
  chevronUp: ChevronUp,
  circleCheckBig: CircleCheckBig,
  circleCheck: CircleCheck,
  circlePlus: CirclePlus,
  circleX: CircleX,
  circuitBoard: CircuitBoard,
  clapperboard: Clapperboard,
  clipboardCheck: ClipboardCheck,
  clipboardList: ClipboardList,
  clipboard: Clipboard,
  clock1: Clock1,
  clock10: Clock10,
  clock11: Clock11,
  clock12: Clock12,
  clock2: Clock2,
  clock3: Clock3,
  clock4: Clock4,
  clock5: Clock5,
  clock6: Clock6,
  clock7: Clock7,
  clock8: Clock8,
  clock9: Clock9,
  clock: Clock,
  cloudDownload: CloudDownload,
  cloudDrizzle: CloudDrizzle,
  cloudHail: CloudHail,
  cloudLightning: CloudLightning,
  cloudMoonRain: CloudMoonRain,
  cloudMoon: CloudMoon,
  cloudRainWind: CloudRainWind,
  cloudRain: CloudRain,
  cloudSnow: CloudSnow,
  cloudSunRain: CloudSunRain,
  cloudSun: CloudSun,
  cloudUpload: CloudUpload,
  cog: Cog,
  compass: Compass,
  contrast: Contrast,
  copy: Copy,
  crop: Crop,
  cross: Cross,
  disc3: Disc3,
  download: Download,
  ellipsisVertical: EllipsisVertical,
  ellipsis: Ellipsis,
  equalNot: EqualNot,
  evCharger: EvCharger,
  expand: Expand,
  externalLink: ExternalLink,
  fan: Fan,
  fingerprint: Fingerprint,
  forklift: Forklift,
  frame: Frame,
  galleryHorizontalEnd: GalleryHorizontalEnd,
  galleryHorizontal: GalleryHorizontal,
  galleryVerticalEnd: GalleryVerticalEnd,
  galleryVertical: GalleryVertical,
  gauge: Gauge,
  gavel: Gavel,
  hammer: Hammer,
  heart: Heart,
  houseWifi: HouseWifi,
  kanban: Kanban,
  layers2: Layers2,
  layers: Layers,
  layoutDashboard: LayoutDashboard,
  lightbulbOff: LightbulbOff,
  lightbulb: Lightbulb,
  link2: Link2,
  link: Link,
  list: List,
  loaderCircle: LoaderCircle,
  loaderPinwheel: LoaderPinwheel,
  loader: Loader,
  lockKeyholeOpen: LockKeyholeOpen,
  lockKeyhole: LockKeyhole,
  lockOpen: LockOpen,
  lock: Lock,
  logIn: LogIn,
  logOut: LogOut,
  mapPinOff: MapPinOff,
  mapPin: MapPin,
  maximize: Maximize,
  menu: Menu,
  messageCircleCode: MessageCircleCode,
  messageCircleDashed: MessageCircleDashed,
  messageCircleHeart: MessageCircleHeart,
  messageCircleMore: MessageCircleMore,
  messageCircleOff: MessageCircleOff,
  messageCirclePlus: MessageCirclePlus,
  messageCircleQuestion: MessageCircleQuestion,
  messageCircleWarning: MessageCircleWarning,
  messageCircleX: MessageCircleX,
  messageCircle: MessageCircle,
  messageSquareCode: MessageSquareCode,
  messageSquareDashed: MessageSquareDashed,
  messageSquareDiff: MessageSquareDiff,
  messageSquareDot: MessageSquareDot,
  messageSquareHeart: MessageSquareHeart,
  messageSquareMore: MessageSquareMore,
  messageSquareOff: MessageSquareOff,
  messageSquarePlus: MessageSquarePlus,
  messageSquareQuote: MessageSquareQuote,
  messageSquareShare: MessageSquareShare,
  messageSquareText: MessageSquareText,
  messageSquareWarning: MessageSquareWarning,
  messageSquareX: MessageSquareX,
  messageSquare: MessageSquare,
  minimize: Minimize,
  moonStar: MoonStar,
  moon: Moon,
  moveDown: MoveDown,
  moveLeft: MoveLeft,
  moveRight: MoveRight,
  moveUp: MoveUp,
  nfc: Nfc,
  orbit: Orbit,
  paintbrush: Paintbrush,
  panelBottomClose: PanelBottomClose,
  panelBottomOpen: PanelBottomOpen,
  panelBottom: PanelBottom,
  panelLeftClose: PanelLeftClose,
  panelLeftOpen: PanelLeftOpen,
  panelLeft: PanelLeft,
  panelRightClose: PanelRightClose,
  panelRightOpen: PanelRightOpen,
  panelRight: PanelRight,
  panelTopClose: PanelTopClose,
  panelTopOpen: PanelTopOpen,
  panelTop: PanelTop,
  paperclip: Paperclip,
  partyPopper: PartyPopper,
  pause: Pause,
  phoneCall: PhoneCall,
  pickaxe: Pickaxe,
  pinOff: PinOff,
  pin: Pin,
  play: Play,
  plugZap: PlugZap,
  plus: Plus,
  radioTower: RadioTower,
  radio: Radio,
  refreshCcwDot: RefreshCcwDot,
  refreshCcw: RefreshCcw,
  refreshCwOff: RefreshCwOff,
  refreshCw: RefreshCw,
  rotateCcw: RotateCcw,
  rotateCw: RotateCw,
  route: Route,
  router: Router,
  scissorsLineDashed: ScissorsLineDashed,
  scissors: Scissors,
  search: Search,
  sendHorizontal: SendHorizontal,
  send: Send,
  settings: Settings,
  shrink: Shrink,
  signalHigh: SignalHigh,
  signalLow: SignalLow,
  signalMedium: SignalMedium,
  signalZero: SignalZero,
  signal: Signal,
  slidersHorizontal: SlidersHorizontal,
  slidersVertical: SlidersVertical,
  sparkle: Sparkle,
  sparkles: Sparkles,
  squareArrowOutDownLeft: SquareArrowOutDownLeft,
  squareArrowOutDownRight: SquareArrowOutDownRight,
  squareArrowOutUpLeft: SquareArrowOutUpLeft,
  squareArrowOutUpRight: SquareArrowOutUpRight,
  squareDashedKanban: SquareDashedKanban,
  squareKanban: SquareKanban,
  squarePlus: SquarePlus,
  squareX: SquareX,
  star: Star,
  sunDim: SunDim,
  sunMedium: SunMedium,
  sunMoon: SunMoon,
  sun: Sun,
  terminal: Terminal,
  thumbsDown: ThumbsDown,
  thumbsUp: ThumbsUp,
  timerOff: TimerOff,
  timer: Timer,
  toggleLeft: ToggleLeft,
  toggleRight: ToggleRight,
  trash2: Trash2,
  trash: Trash,
  unplug: Unplug,
  upload: Upload,
  userRound: UserRound,
  user: User,
  usersRound: UsersRound,
  users: Users,
  volume1: Volume1,
  volume2: Volume2,
  volumeOff: VolumeOff,
  wifiHigh: WifiHigh,
  wifiLow: WifiLow,
  wifiZero: WifiZero,
  wifi: Wifi,
  x: X,
} as const;

type IconName = keyof typeof icons;

// biome-ignore lint/suspicious/noExplicitAny: lint debt cleanup
function keys<T extends Record<string, any>>(obj: T): Array<keyof T> {
  return Object.keys(obj) as Array<keyof T>;
}

const iconNames = keys(icons) as [IconName, ...IconName[]];

const AnimatedIconSchema = z.object({
  name: z.enum(iconNames).default('wifi'),
  className: z.string().optional(),
  animateOnHover: z.boolean().default(true),
  size: z.enum(['small', 'medium', 'large']).default('medium'),
  color: z
    .enum([
      'accent',
      'accentForeground',
      'primary',
      'primaryForeground',
      'secondary',
      'secondaryForeground',
      'destructive',
      'destructiveForeground',
      'muted',
      'mutedForeground',
      'background',
      'foreground',
    ])
    .optional(),
});

type AnimatedIconProps = z.infer<typeof AnimatedIconSchema> &
  Omit<SVGMotionProps<SVGSVGElement>, 'animate'>;

const AnimatedIcon = ({
  name,
  size = 'medium',
  color,
  animateOnHover = true,
  className = '',
  ...props
}: AnimatedIconProps) => {
  const IconComponent = icons[name];

  if (!IconComponent) {
    console.error(`Animated icon with name "${name}" not found`);
    return null;
  }

  const sizeClass = sizeClasses[size];
  const colorClass =
    color && typeof color === 'string' ? colorClasses[color] : '';
  const combinedClassName = [sizeClass, colorClass, className]
    .filter(Boolean)
    .join(' ');

  return (
    <IconComponent
      className={combinedClassName}
      {...props}
      animateOnHover={animateOnHover}
    />
  );
};

export { AnimatedIcon, type IconName, AnimatedIconSchema };
