import fs from 'fs';
import path from 'path';
import { extractSchemas } from './extract.js';
import { resolveType } from './flatten.js';
import type { ZodTypegenOptions } from './index.js';

export function generate(options: ZodTypegenOptions) {
  const { project, schemas } = extractSchemas(options.entry);
  const checker = project.getTypeChecker();
  const sourceFile = project.getSourceFile(options.entry);
  if (!sourceFile) return;

  // Pre-resolve all schema types to enable cross-schema identity matching
  const schemaInfos = schemas.map(s => {
    const v = sourceFile.getVariableDeclaration(s.identifier);
    if (!v) return null;
    const type = v.getType();
    
    let outputSymbol = type.getProperty('_output');
    // Support CreatedSchema wrapper which has a schemaShape property
    if (!outputSymbol) {
      const schemaShapeSymbol = type.getProperty('schemaShape');
      if (schemaShapeSymbol) {
        const schemaShapeType = checker.getTypeOfSymbolAtLocation(schemaShapeSymbol, v.getNameNode());
        outputSymbol = schemaShapeType.getProperty('_output');
      }
    }

    if (!outputSymbol) return null;

    return {
      name: s.name,
      identifier: s.identifier,
      type: checker.getTypeOfSymbolAtLocation(outputSymbol, v.getNameNode()),
      variable: v
    };
  }).filter((s): s is any => s !== null);
  
  let content = '/* eslint-disable */\n';
  content += '/* This file is auto-generated by zod-typegen. Do not edit manually. */\n\n';
  content += 'declare global {\n';
  
  for (const info of schemaInfos) {
    const resolved = resolveType(info.type, checker, info.name, info.variable.getNameNode(), schemaInfos);
    
    if (resolved.trim().startsWith('{')) {
      content += `  interface ${info.name} ${resolved}\n\n`;
    } else {
      content += `  type ${info.name} = ${resolved};\n\n`;
    }
  }
  
  content += '}\n\nexport {};\n';
  
  const outputDir = path.dirname(options.output);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }
  
  fs.writeFileSync(options.output, content);
  console.log(`[zod-typegen] Generated ${options.output}`);
}
