import fs from 'fs';
import path from 'path';
import type { ZodTypegenOptions } from './index.js';
import { extractDefaultSchema } from './extract.js';

export function generate(options: ZodTypegenOptions) {
  const { project, schema } = extractDefaultSchema(options.entry);
  const checker = project.getTypeChecker();
  const sourceFile = project.getSourceFile(options.entry);
  if (!sourceFile) return;

  if (!schema) return;

  function getSchemaInfo() {
    const v = sourceFile!.getVariableDeclaration(schema!.identifier);
    if (!v) return null;
    const type = v.getType();

    let outputSymbol = type.getProperty('_output');
    // Support CreatedSchema wrapper which has a schemaShape property
    if (!outputSymbol) {
      const schemaShapeSymbol = type.getProperty('schemaShape');
      if (schemaShapeSymbol) {
        const schemaShapeType = checker.getTypeOfSymbolAtLocation(schemaShapeSymbol, v.getNameNode());
        outputSymbol = schemaShapeType.getProperty('_output');
      }
    }

    if (!outputSymbol) return null;

    return {
      name: schema!.name,
      identifier: schema!.identifier,
      typeText: v.getType()?.getText(
        // v,
        // ts.TypeFormatFlags.NoTruncation | ts.TypeFormatFlags.InTypeAlias
      ),
      variable: v
    };
  }

  const schemaInfo = getSchemaInfo();

  if (!schemaInfo) return;

  const content = `
  /* eslint-disable */
  /* This file is auto-generated by zod-typegen. Do not edit manually. */

  declare global {
    type ${schemaInfo.name} = ${schemaInfo.typeText};
  }

  export {};
  `

  const outputDir = path.dirname(options.output);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(options.output, content);
  console.log(`[zod-typegen] Generated ${options.output}`);
}
