/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AdminImport } from './routes/admin'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as BusinessChatImport } from './routes/_business/chat'
import { Route as AuthAuthImport } from './routes/_auth/auth'
import { Route as BusinessRideIndexImport } from './routes/_business/ride/index'
import { Route as BusinessSchoolSasaImport } from './routes/_business/_school/sasa'
import { Route as BusinessRetailAnjalstoreImport } from './routes/_business/_retail/anjalstore'
import { Route as BusinessRideAdminRouteImport } from './routes/_business/ride/admin/route'
import { Route as BusinessRideAdminIndexImport } from './routes/_business/ride/admin/index'
import { Route as AuthDemosRestaurantIndexImport } from './routes/_auth/_demos/restaurant/index'
import { Route as BusinessRideAdminVehicleTypesImport } from './routes/_business/ride/admin/vehicle-types'
import { Route as AuthDemosRestaurantAdminImport } from './routes/_auth/_demos/restaurant/admin'

// Create/Update Routes

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BusinessChatRoute = BusinessChatImport.update({
  id: '/_business/chat',
  path: '/chat',
  getParentRoute: () => rootRoute,
} as any)

const AuthAuthRoute = AuthAuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => AuthRoute,
} as any)

const BusinessRideIndexRoute = BusinessRideIndexImport.update({
  id: '/_business/ride/',
  path: '/ride/',
  getParentRoute: () => rootRoute,
} as any)

const BusinessSchoolSasaRoute = BusinessSchoolSasaImport.update({
  id: '/_business/_school/sasa',
  path: '/sasa',
  getParentRoute: () => rootRoute,
} as any)

const BusinessRetailAnjalstoreRoute = BusinessRetailAnjalstoreImport.update({
  id: '/_business/_retail/anjalstore',
  path: '/anjalstore',
  getParentRoute: () => rootRoute,
} as any)

const BusinessRideAdminRouteRoute = BusinessRideAdminRouteImport.update({
  id: '/_business/ride/admin',
  path: '/ride/admin',
  getParentRoute: () => rootRoute,
} as any)

const BusinessRideAdminIndexRoute = BusinessRideAdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BusinessRideAdminRouteRoute,
} as any)

const AuthDemosRestaurantIndexRoute = AuthDemosRestaurantIndexImport.update({
  id: '/_demos/restaurant/',
  path: '/restaurant/',
  getParentRoute: () => AuthRoute,
} as any)

const BusinessRideAdminVehicleTypesRoute =
  BusinessRideAdminVehicleTypesImport.update({
    id: '/vehicle-types',
    path: '/vehicle-types',
    getParentRoute: () => BusinessRideAdminRouteRoute,
  } as any)

const AuthDemosRestaurantAdminRoute = AuthDemosRestaurantAdminImport.update({
  id: '/_demos/restaurant/admin',
  path: '/restaurant/admin',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/_auth/auth': {
      id: '/_auth/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthImport
      parentRoute: typeof AuthImport
    }
    '/_business/chat': {
      id: '/_business/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof BusinessChatImport
      parentRoute: typeof rootRoute
    }
    '/_business/ride/admin': {
      id: '/_business/ride/admin'
      path: '/ride/admin'
      fullPath: '/ride/admin'
      preLoaderRoute: typeof BusinessRideAdminRouteImport
      parentRoute: typeof rootRoute
    }
    '/_business/_retail/anjalstore': {
      id: '/_business/_retail/anjalstore'
      path: '/anjalstore'
      fullPath: '/anjalstore'
      preLoaderRoute: typeof BusinessRetailAnjalstoreImport
      parentRoute: typeof rootRoute
    }
    '/_business/_school/sasa': {
      id: '/_business/_school/sasa'
      path: '/sasa'
      fullPath: '/sasa'
      preLoaderRoute: typeof BusinessSchoolSasaImport
      parentRoute: typeof rootRoute
    }
    '/_business/ride/': {
      id: '/_business/ride/'
      path: '/ride'
      fullPath: '/ride'
      preLoaderRoute: typeof BusinessRideIndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth/_demos/restaurant/admin': {
      id: '/_auth/_demos/restaurant/admin'
      path: '/restaurant/admin'
      fullPath: '/restaurant/admin'
      preLoaderRoute: typeof AuthDemosRestaurantAdminImport
      parentRoute: typeof AuthImport
    }
    '/_business/ride/admin/vehicle-types': {
      id: '/_business/ride/admin/vehicle-types'
      path: '/vehicle-types'
      fullPath: '/ride/admin/vehicle-types'
      preLoaderRoute: typeof BusinessRideAdminVehicleTypesImport
      parentRoute: typeof BusinessRideAdminRouteImport
    }
    '/_auth/_demos/restaurant/': {
      id: '/_auth/_demos/restaurant/'
      path: '/restaurant'
      fullPath: '/restaurant'
      preLoaderRoute: typeof AuthDemosRestaurantIndexImport
      parentRoute: typeof AuthImport
    }
    '/_business/ride/admin/': {
      id: '/_business/ride/admin/'
      path: '/'
      fullPath: '/ride/admin/'
      preLoaderRoute: typeof BusinessRideAdminIndexImport
      parentRoute: typeof BusinessRideAdminRouteImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthAuthRoute: typeof AuthAuthRoute
  AuthDemosRestaurantAdminRoute: typeof AuthDemosRestaurantAdminRoute
  AuthDemosRestaurantIndexRoute: typeof AuthDemosRestaurantIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthRoute: AuthAuthRoute,
  AuthDemosRestaurantAdminRoute: AuthDemosRestaurantAdminRoute,
  AuthDemosRestaurantIndexRoute: AuthDemosRestaurantIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface BusinessRideAdminRouteRouteChildren {
  BusinessRideAdminVehicleTypesRoute: typeof BusinessRideAdminVehicleTypesRoute
  BusinessRideAdminIndexRoute: typeof BusinessRideAdminIndexRoute
}

const BusinessRideAdminRouteRouteChildren: BusinessRideAdminRouteRouteChildren =
  {
    BusinessRideAdminVehicleTypesRoute: BusinessRideAdminVehicleTypesRoute,
    BusinessRideAdminIndexRoute: BusinessRideAdminIndexRoute,
  }

const BusinessRideAdminRouteRouteWithChildren =
  BusinessRideAdminRouteRoute._addFileChildren(
    BusinessRideAdminRouteRouteChildren,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthAuthRoute
  '/chat': typeof BusinessChatRoute
  '/ride/admin': typeof BusinessRideAdminRouteRouteWithChildren
  '/anjalstore': typeof BusinessRetailAnjalstoreRoute
  '/sasa': typeof BusinessSchoolSasaRoute
  '/ride': typeof BusinessRideIndexRoute
  '/restaurant/admin': typeof AuthDemosRestaurantAdminRoute
  '/ride/admin/vehicle-types': typeof BusinessRideAdminVehicleTypesRoute
  '/restaurant': typeof AuthDemosRestaurantIndexRoute
  '/ride/admin/': typeof BusinessRideAdminIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthAuthRoute
  '/chat': typeof BusinessChatRoute
  '/anjalstore': typeof BusinessRetailAnjalstoreRoute
  '/sasa': typeof BusinessSchoolSasaRoute
  '/ride': typeof BusinessRideIndexRoute
  '/restaurant/admin': typeof AuthDemosRestaurantAdminRoute
  '/ride/admin/vehicle-types': typeof BusinessRideAdminVehicleTypesRoute
  '/restaurant': typeof AuthDemosRestaurantIndexRoute
  '/ride/admin': typeof BusinessRideAdminIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/admin': typeof AdminRoute
  '/_auth/auth': typeof AuthAuthRoute
  '/_business/chat': typeof BusinessChatRoute
  '/_business/ride/admin': typeof BusinessRideAdminRouteRouteWithChildren
  '/_business/_retail/anjalstore': typeof BusinessRetailAnjalstoreRoute
  '/_business/_school/sasa': typeof BusinessSchoolSasaRoute
  '/_business/ride/': typeof BusinessRideIndexRoute
  '/_auth/_demos/restaurant/admin': typeof AuthDemosRestaurantAdminRoute
  '/_business/ride/admin/vehicle-types': typeof BusinessRideAdminVehicleTypesRoute
  '/_auth/_demos/restaurant/': typeof AuthDemosRestaurantIndexRoute
  '/_business/ride/admin/': typeof BusinessRideAdminIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/admin'
    | '/auth'
    | '/chat'
    | '/ride/admin'
    | '/anjalstore'
    | '/sasa'
    | '/ride'
    | '/restaurant/admin'
    | '/ride/admin/vehicle-types'
    | '/restaurant'
    | '/ride/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/admin'
    | '/auth'
    | '/chat'
    | '/anjalstore'
    | '/sasa'
    | '/ride'
    | '/restaurant/admin'
    | '/ride/admin/vehicle-types'
    | '/restaurant'
    | '/ride/admin'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/admin'
    | '/_auth/auth'
    | '/_business/chat'
    | '/_business/ride/admin'
    | '/_business/_retail/anjalstore'
    | '/_business/_school/sasa'
    | '/_business/ride/'
    | '/_auth/_demos/restaurant/admin'
    | '/_business/ride/admin/vehicle-types'
    | '/_auth/_demos/restaurant/'
    | '/_business/ride/admin/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AdminRoute: typeof AdminRoute
  BusinessChatRoute: typeof BusinessChatRoute
  BusinessRideAdminRouteRoute: typeof BusinessRideAdminRouteRouteWithChildren
  BusinessRetailAnjalstoreRoute: typeof BusinessRetailAnjalstoreRoute
  BusinessSchoolSasaRoute: typeof BusinessSchoolSasaRoute
  BusinessRideIndexRoute: typeof BusinessRideIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AdminRoute: AdminRoute,
  BusinessChatRoute: BusinessChatRoute,
  BusinessRideAdminRouteRoute: BusinessRideAdminRouteRouteWithChildren,
  BusinessRetailAnjalstoreRoute: BusinessRetailAnjalstoreRoute,
  BusinessSchoolSasaRoute: BusinessSchoolSasaRoute,
  BusinessRideIndexRoute: BusinessRideIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/admin",
        "/_business/chat",
        "/_business/ride/admin",
        "/_business/_retail/anjalstore",
        "/_business/_school/sasa",
        "/_business/ride/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/auth",
        "/_auth/_demos/restaurant/admin",
        "/_auth/_demos/restaurant/"
      ]
    },
    "/admin": {
      "filePath": "admin.tsx"
    },
    "/_auth/auth": {
      "filePath": "_auth/auth.tsx",
      "parent": "/_auth"
    },
    "/_business/chat": {
      "filePath": "_business/chat.tsx"
    },
    "/_business/ride/admin": {
      "filePath": "_business/ride/admin/route.tsx",
      "children": [
        "/_business/ride/admin/vehicle-types",
        "/_business/ride/admin/"
      ]
    },
    "/_business/_retail/anjalstore": {
      "filePath": "_business/_retail/anjalstore.tsx"
    },
    "/_business/_school/sasa": {
      "filePath": "_business/_school/sasa.tsx"
    },
    "/_business/ride/": {
      "filePath": "_business/ride/index.tsx"
    },
    "/_auth/_demos/restaurant/admin": {
      "filePath": "_auth/_demos/restaurant/admin.tsx",
      "parent": "/_auth"
    },
    "/_business/ride/admin/vehicle-types": {
      "filePath": "_business/ride/admin/vehicle-types.tsx",
      "parent": "/_business/ride/admin"
    },
    "/_auth/_demos/restaurant/": {
      "filePath": "_auth/_demos/restaurant/index.tsx",
      "parent": "/_auth"
    },
    "/_business/ride/admin/": {
      "filePath": "_business/ride/admin/index.tsx",
      "parent": "/_business/ride/admin"
    }
  }
}
ROUTE_MANIFEST_END */
