name = "gun-relay"
main = "src/index.ts"
compatibility_date = "2024-02-15"

[vars]
GUN_PEERS = ""

[[durable_objects.bindings]]
name = "RELAY"
class_name = "GunRelay"

[[migrations]]
tag = "v1"
name = "initial-migration"
new_sqlite_classes = ["GunRelay"]

[triggers]
crons = []

# Define routes to your worker.  Websocket requests must go to the DO.
# [[routes]]
# pattern = "/gun"  #  Route ALL requests with /gun to your worker