/* eslint-disable */
/* This file is auto-generated by zod-typegen. Do not edit manually. */

declare global {
  interface PermissionSchema { [key: string]: boolean }

  interface RoleSchema {
    name?: string;
    permissions?: PermissionSchema;
    timestamp?: number;
    created_by?: string;
  }

  interface UserSchema {
    name?: string;
    timestamp?: number;
    created_by?: string;
    email?: string;
    password?: string;
    avatar?: any;
    phone?: string;
    isActive?: boolean;
    role?: 'user' | 'internal-staff' | 'admin';
  }

  interface OtpSchema {
    timestamp?: number;
    created_by?: string;
    otp?: string;
  }

  interface BusinessMemberSchema {
    permissions?: PermissionSchema;
    role?: 'owner' | 'staff';
    userId?: string;
    joinedAt?: number;
  }

  interface BusinessInvitationSchema {
    permissions?: PermissionSchema;
    email?: string;
    role?: 'owner' | 'staff';
    invitedAt?: number;
    token?: string;
    expiresAt?: number;
  }

  type BusinessTypeSchema = 'retail';

  interface BusinessSchema {
    name?: string;
    timestamp?: number;
    created_by?: string;
    isActive?: boolean;
    id?: string;
    location?: string;
    basePath?: string;
    businessType?: 'retail';
    features?: any;
    icon?: string;
    members?: { [key: string]: BusinessMemberSchema };
    invitations?: { [key: string]: BusinessInvitationSchema };
    uiBuilder?: {
    layers?: any;
    timestamp?: any;
    created_by?: any;
  };
  }

  type PartySchema = CustomerSchema;

  type CustomerSchema = PartySchema;

  interface InvoiceSchema {
    type?: 'purchase' | 'sale';
    description?: any;
    timestamp?: number;
    created_by?: string;
    partyId?: string;
    vehicleId?: string;
    tripId?: string;
    issuedAt?: string;
    dueDate?: string;
    items?: {
    product?: string;
    quantity?: number;
    rate?: number;
    total?: number;
  }[];
    subTotal?: number;
    tax?: number;
    paidAmount?: number;
    paymentStatus?: any;
    fiscalYear?: string;
  }

  type VehicleIdSchema = string;

  interface TripSchema {
    timestamp?: number;
    created_by?: string;
    vehicleId?: string;
    dispatchTime?: any;
    returnTime?: string;
    destination?: string;
    products?: {
    timestamp?: number;
    created_by?: string;
    product?: string;
    quantity?: number;
    unit?: any;
    unitPrice?: number;
    totalAmount?: any;
  }[];
    returnedProducts?: {
    timestamp?: number;
    created_by?: string;
    product?: string;
    quantity?: number;
    unit?: any;
    unitPrice?: number;
    totalAmount?: any;
  }[];
  }

  interface MembershipSchema {
    timestamp?: number;
    created_by?: string;
    userId?: string;
    businessId?: string;
    roleId?: string;
  }

  type CustomerIdSchema = string;

  interface OrderSchema {
    timestamp?: number;
    created_by?: string;
    notes?: any;
    items?: {
    timestamp?: number;
    created_by?: string;
    product?: string;
    quantity?: number;
    unit?: any;
    unitPrice?: number;
    totalAmount?: any;
  }[];
    paidAmount?: number;
    paymentStatus?: any;
    customerId?: string;
    orderStatus?: 'pending' | 'done' | 'cancelled';
    paymentMethod?: 'cash' | 'card' | 'bankTransfer' | 'credit';
  }

  interface RecentlyUsedAppSchema {
    timestamp?: number;
    created_by?: string;
    appId?: string;
    usageCount?: number;
  }

  interface CoreSchema {
    user?: UserSchema;
    role?: RoleSchema;
    otp?: OtpSchema;
    business?: BusinessSchema;
    membership?: MembershipSchema;
  }

  interface FeatureSchema {
    sale?: {
    timestamp?: number;
    created_by?: string;
    notes?: any;
    items?: {
    timestamp?: number;
    created_by?: string;
    product?: string;
    quantity?: number;
    unit?: any;
    unitPrice?: number;
    totalAmount?: any;
  }[];
    paidAmount?: number;
    paymentStatus?: any;
    customerId?: string;
    paymentMethod?: 'cash' | 'card' | 'bankTransfer' | 'credit';
    saleDate?: any;
  };
    product?: {
    description?: any;
    timestamp?: number;
    created_by?: string;
    isActive?: boolean;
    unit?: any;
    title?: string;
    hsCode?: string;
    costPrice?: number;
    sellingPrice?: any;
    stockQuantity?: any;
    barcode?: string;
    reorderLevel?: any;
    category?: string;
    sku?: string;
    imageUrl?: string;
    isFeatured?: boolean;
  };
    order?: OrderSchema;
    party?: PartySchema;
    customer?: PartySchema;
    invoice?: InvoiceSchema;
    stockImport?: {
    timestamp?: number;
    created_by?: string;
    notes?: any;
    items?: {
    timestamp?: number;
    created_by?: string;
    product?: string;
    quantity?: number;
    unit?: any;
    unitPrice?: number;
    totalAmount?: any;
  }[];
    paidAmount?: number;
    paymentStatus?: any;
    party?: string;
    importDate?: any;
  };
    menuItem?: {
    description?: any;
    timestamp?: number;
    created_by?: string;
    isActive?: boolean;
    unit?: any;
    title?: string;
    hsCode?: string;
    costPrice?: number;
    sellingPrice?: any;
    stockQuantity?: any;
    barcode?: string;
    reorderLevel?: any;
    category?: string;
    sku?: string;
    imageUrl?: string;
    isFeatured?: boolean;
    isVegetarian?: boolean;
    isSpicy?: boolean;
    isSpecial?: boolean;
    preparationTime?: number;
  };
    dataMatrixAction?: {
    product?: {
    id?: string;
    sku?: string;
  };
    version?: string;
    action?: 'wifi_connect' | 'profile_enrichment' | 'equipment_session' | 'restaurant_ordering' | 'product_interaction' | 'navigate' | 'form_request' | 'choice_selection' | 'notification' | 'equipment_control';
    wifi?: {
    password?: string;
    ssid?: string;
    security?: 'WPA2' | 'WPA3' | 'WEP' | 'open';
  };
    navigation?: {
    params?: { [key: string]: string | number | undefined };
    url?: string;
  };
    post_connect?: {
    notification?: {
    message?: string;
    title?: string;
  };
  };
    checks?: {
    required?: boolean;
    field?: string;
    if_missing?: {
    options?: {
    value?: string;
    label?: string;
  }[];
    type?: 'form_request' | 'choice_selection';
    schema?: {
    title?: string;
    fields?: {
    type?: string;
    label?: string;
    name?: string;
    required?: boolean;
  }[];
  };
    multiple?: boolean;
  };
  }[];
    on_complete?: {
    message?: string;
    type?: 'navigate' | 'notification';
    url?: string;
  };
    equipment?: {
    type?: string;
    id?: string;
    location?: string;
  };
    session?: {
    duration?: number;
    max_duration?: number;
    extendable?: boolean;
  };
    user_validation?: {
    membership_required?: boolean;
    min_fitness_level?: string;
  };
    actions?: {
    on_start?: {
    type?: 'equipment_control';
    command?: 'activate';
    parameters?: { [key: string]: string };
  };
    on_extend?: {
    message?: string;
    type?: 'confirm';
    actions?: {
    confirm?: {
    type?: 'equipment_control';
    duration?: number;
    command?: 'extend_session';
  };
  };
  };
    on_end?: {
    type?: 'equipment_control';
    command?: 'deactivate';
  };
  };
    restaurant?: {
    id?: string;
    table?: string;
  };
    flow?: {
    steps?: {
    options?: 'cash' | 'card' | 'mobile_payment'[];
    validation?: {
    allergen_check?: boolean;
    preparation_time?: string;
  };
    type?: 'menu_display' | 'order_building' | 'order_confirmation' | 'payment_selection';
    features?: {
    customization?: boolean;
    special_requests?: boolean;
    combo_suggestions?: boolean;
  };
    step?: number;
    categories?: string[];
    filters?: {
    dietary?: string;
    availability?: string;
  };
    tip_suggestions?: number[];
  }[];
  };
    interactions?: {
    purchase?: {
    options?: {
    delivery?: 'in_store' | 'home_delivery'[];
    payment?: string[];
  };
    type?: 'quick_buy';
  };
    info?: {
    type?: 'product_details';
    sections?: string[];
  };
    demo?: {
    type?: 'ar_experience';
    features?: string[];
    model?: string;
  };
    compare?: {
    type?: 'product_comparison';
    related_products?: string[];
  };
  };
  };
    recentlyUsedApp?: RecentlyUsedAppSchema;
    folder?: {
    name?: string;
    timestamp?: number;
    created_by?: string;
    userId?: string;
    apps?: PermissionSchema;
  };
    qrFlowConfig?: {
    description?: string;
    timestamp?: number;
    created_by?: string;
    id?: string;
    title?: string;
    nodes?: {
    type?: string;
    id?: string;
    position?: {
    x?: number;
    y?: number;
  };
    data?: {
    status?: string;
    label?: string;
    description?: string;
    config?: { [key: string]: any };
    stats?: {
    started?: number;
    running?: number;
    completed?: number;
    error?: number;
    progress?: number;
  };
  };
  }[];
    edges?: {
    type?: string;
    id?: string;
    target?: string;
    data?: { [key: string]: any };
    source?: string;
    sourceHandle?: string;
    targetHandle?: string;
  }[];
    nodeLibraryOrder?: {
    type?: string;
    label?: string;
    color?: string;
    order?: number;
  }[];
    createdAt?: number;
    updatedAt?: number;
    revision?: number;
  };
    vehicle?: {
    description?: any;
    name?: string;
    timestamp?: number;
    created_by?: string;
    licensePlate?: string;
  };
    trip?: TripSchema;
  }

  interface AppSchema {
    user?: UserSchema;
    role?: RoleSchema;
    otp?: OtpSchema;
    sale?: {
    timestamp?: number;
    created_by?: string;
    notes?: any;
    items?: {
    timestamp?: number;
    created_by?: string;
    product?: string;
    quantity?: number;
    unit?: any;
    unitPrice?: number;
    totalAmount?: any;
  }[];
    paidAmount?: number;
    paymentStatus?: any;
    customerId?: string;
    paymentMethod?: 'cash' | 'card' | 'bankTransfer' | 'credit';
    saleDate?: any;
  };
    product?: {
    description?: any;
    timestamp?: number;
    created_by?: string;
    isActive?: boolean;
    unit?: any;
    title?: string;
    hsCode?: string;
    costPrice?: number;
    sellingPrice?: any;
    stockQuantity?: any;
    barcode?: string;
    reorderLevel?: any;
    category?: string;
    sku?: string;
    imageUrl?: string;
    isFeatured?: boolean;
  };
    order?: OrderSchema;
    business?: BusinessSchema;
    membership?: MembershipSchema;
    party?: PartySchema;
    customer?: PartySchema;
    invoice?: InvoiceSchema;
    stockImport?: {
    timestamp?: number;
    created_by?: string;
    notes?: any;
    items?: {
    timestamp?: number;
    created_by?: string;
    product?: string;
    quantity?: number;
    unit?: any;
    unitPrice?: number;
    totalAmount?: any;
  }[];
    paidAmount?: number;
    paymentStatus?: any;
    party?: string;
    importDate?: any;
  };
    menuItem?: {
    description?: any;
    timestamp?: number;
    created_by?: string;
    isActive?: boolean;
    unit?: any;
    title?: string;
    hsCode?: string;
    costPrice?: number;
    sellingPrice?: any;
    stockQuantity?: any;
    barcode?: string;
    reorderLevel?: any;
    category?: string;
    sku?: string;
    imageUrl?: string;
    isFeatured?: boolean;
    isVegetarian?: boolean;
    isSpicy?: boolean;
    isSpecial?: boolean;
    preparationTime?: number;
  };
    dataMatrixAction?: {
    product?: {
    id?: string;
    sku?: string;
  };
    version?: string;
    action?: 'wifi_connect' | 'profile_enrichment' | 'equipment_session' | 'restaurant_ordering' | 'product_interaction' | 'navigate' | 'form_request' | 'choice_selection' | 'notification' | 'equipment_control';
    wifi?: {
    password?: string;
    ssid?: string;
    security?: 'WPA2' | 'WPA3' | 'WEP' | 'open';
  };
    navigation?: {
    params?: { [key: string]: string | number | undefined };
    url?: string;
  };
    post_connect?: {
    notification?: {
    message?: string;
    title?: string;
  };
  };
    checks?: {
    required?: boolean;
    field?: string;
    if_missing?: {
    options?: {
    value?: string;
    label?: string;
  }[];
    type?: 'form_request' | 'choice_selection';
    schema?: {
    title?: string;
    fields?: {
    type?: string;
    label?: string;
    name?: string;
    required?: boolean;
  }[];
  };
    multiple?: boolean;
  };
  }[];
    on_complete?: {
    message?: string;
    type?: 'navigate' | 'notification';
    url?: string;
  };
    equipment?: {
    type?: string;
    id?: string;
    location?: string;
  };
    session?: {
    duration?: number;
    max_duration?: number;
    extendable?: boolean;
  };
    user_validation?: {
    membership_required?: boolean;
    min_fitness_level?: string;
  };
    actions?: {
    on_start?: {
    type?: 'equipment_control';
    command?: 'activate';
    parameters?: { [key: string]: string };
  };
    on_extend?: {
    message?: string;
    type?: 'confirm';
    actions?: {
    confirm?: {
    type?: 'equipment_control';
    duration?: number;
    command?: 'extend_session';
  };
  };
  };
    on_end?: {
    type?: 'equipment_control';
    command?: 'deactivate';
  };
  };
    restaurant?: {
    id?: string;
    table?: string;
  };
    flow?: {
    steps?: {
    options?: 'cash' | 'card' | 'mobile_payment'[];
    validation?: {
    allergen_check?: boolean;
    preparation_time?: string;
  };
    type?: 'menu_display' | 'order_building' | 'order_confirmation' | 'payment_selection';
    features?: {
    customization?: boolean;
    special_requests?: boolean;
    combo_suggestions?: boolean;
  };
    step?: number;
    categories?: string[];
    filters?: {
    dietary?: string;
    availability?: string;
  };
    tip_suggestions?: number[];
  }[];
  };
    interactions?: {
    purchase?: {
    options?: {
    delivery?: 'in_store' | 'home_delivery'[];
    payment?: string[];
  };
    type?: 'quick_buy';
  };
    info?: {
    type?: 'product_details';
    sections?: string[];
  };
    demo?: {
    type?: 'ar_experience';
    features?: string[];
    model?: string;
  };
    compare?: {
    type?: 'product_comparison';
    related_products?: string[];
  };
  };
  };
    recentlyUsedApp?: RecentlyUsedAppSchema;
    folder?: {
    name?: string;
    timestamp?: number;
    created_by?: string;
    userId?: string;
    apps?: PermissionSchema;
  };
    qrFlowConfig?: {
    description?: string;
    timestamp?: number;
    created_by?: string;
    id?: string;
    title?: string;
    nodes?: {
    type?: string;
    id?: string;
    position?: {
    x?: number;
    y?: number;
  };
    data?: {
    status?: string;
    label?: string;
    description?: string;
    config?: { [key: string]: any };
    stats?: {
    started?: number;
    running?: number;
    completed?: number;
    error?: number;
    progress?: number;
  };
  };
  }[];
    edges?: {
    type?: string;
    id?: string;
    target?: string;
    data?: { [key: string]: any };
    source?: string;
    sourceHandle?: string;
    targetHandle?: string;
  }[];
    nodeLibraryOrder?: {
    type?: string;
    label?: string;
    color?: string;
    order?: number;
  }[];
    createdAt?: number;
    updatedAt?: number;
    revision?: number;
  };
    vehicle?: {
    description?: any;
    name?: string;
    timestamp?: number;
    created_by?: string;
    licensePlate?: string;
  };
    trip?: TripSchema;
  }

}

export {};
