/* eslint-disable */
/* This file is auto-generated by zod-typegen. Do not edit manually. */

declare global {
  type BaseAppSchemaType =
    import("../lib/schemas/core/types").CreatedSchema<{
     [table: string]: {
     schema: import("../lib/schemas/core/types").DefaultSchemaType;
     title?: string | undefined;
     icon?: React.ForwardRefExoticComponent<Omit<import("lucide-react").LucideProps, "ref"> & React.RefAttributes<SVGSVGElement>> | undefined;
     group?: string | undefined;
     components?: (() => {
     name: string;
     icon?: import("lucide-react").LucideIcon | undefined;
     component: import("../components/ui/admin/index").AdminComponent;
    }[]) | undefined;
    };
    }>;
}

export {};
